name: example
description: An XMTP example app.
publish_to: none
version: 0.0.1
environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  async: ^2.9.0
  blockies_ethereum: ^0.0.2
  convert: ^3.1.1
  drift: ^2.3.0
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_hooks: ^0.18.5+1
  go_router: ^5.2.2
  intl: ^0.18.0
  path: ^1.8.2
  path_provider: ^2.0.0
  retry: ^3.1.0
  shared_preferences: ^2.0.15
  sqlcipher_flutter_libs: ^0.5.1
  sqlite3: ^1.9.1
  web3dart: ^2.5.1
  xmtp:
    path: '../'

dev_dependencies:
  build_runner: ^2.3.2
  drift_dev: ^2.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
