name: xmtp
description: XMTP client SDK for Flutter applications.
version: 0.0.1
publish_to: none # TODO cut when ready to publish
repository: https://github.com/xmtp/xmtp-flutter

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  xmtp_proto: ^0.0.1-development
  pointycastle: ^3.6.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
