name: Release dry run
on:
  push:
    branches:
      - ea/add-release-action
jobs:
  dart:
    name: Release (dart)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.6'
          channel: 'stable'
      - run: docker-compose -p xmtp -f "tool/local-node/docker-compose.yml" up -d
      - run: flutter pub get
      - run: flutter test --dart-define=TEST_SERVER_ENABLED=true
      - run: docker-compose -p xmtp -f "tool/local-node/docker-compose.yml" down
        if: always()
#      - name: Set release version
#        run: |
#          TAG=`echo ${GITHUB_REF#refs/*/}`
#          echo "GIT_TAG=${TAG#v}" >> $GITHUB_ENV
      - name: Set release version
        run: |
          echo "GIT_TAG=0.0.3" >> $GITHUB_ENV
      - name: Prepublish
        env:
          RELEASE_VERSION: ${{ env.GIT_TAG }}
        run: |
          sed -i "s/version: 0.0.0/version: $RELEASE_VERSION/" ./pubspec.yaml
      - name: Verify pubspec
        run: cat ./pubspec.yaml
      - run: dart pub publish --dry-run
